### ISSUE TITLE
Running Dusk 5 + Laravel 5.8 and nothing shows in frame when running tests

### ISSUE THREAD

**Issue by Braunson** [beyondcode/dusk-dashboard#37]
- Running Dusk 5 + Laravel 5.8 + Latest Dusk Dashboard
- Running inside Homstead
- When I click "start tests" it runs through the tests on the left hand side and the console (SSH) shows the tests running also but the frame that should show the site being tested shows nothing (it's completely white and empty).

Any ideas?

Here's my `DuskTestCase.php` which is used in all Dusk tests.

```php
<?php

namespace Tests;

use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use BeyondCode\DuskDashboard\Testing\TestCase as BaseTestCase;

abstract class DuskTestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Prepare for Dusk test execution.
     *
     * @beforeClass
     * @return void
     */
    public static function prepare()
    {
        static::startChromeDriver();
    }

    /**
     * Create the RemoteWebDriver instance.
     *
     * @return \Facebook\WebDriver\Remote\RemoteWebDriver
     */
    protected function driver()
    {
        $options = (new ChromeOptions)->addArguments([
            '--disable-gpu',
            '--headless',
            '--window-size=1920,1080',
        ]);

        return RemoteWebDriver::create(
            'http://localhost:9515', $this->enableNetworkLogging(
                DesiredCapabilities::chrome()->setCapability(
                    ChromeOptions::CAPABILITY, $options
                )
            )
        );
    }
}
```

**Comment by Brotzka** [comment]
I have the same problem. But taking a look at my terminal, there show up a fatal error everytime I click "Start Tests".

The error says:
PHP Fatal error:  Declaration of 

> BeyondCode\DuskDashboard\Testing\TestCase::onNotSuccessfulTest(Throwable $t) must be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t): void in /home/vagrant/faaren/repositories/website-and-consumer-area/vendor/beyondcode/dusk-dashboard/src/Testing/TestCase.php on line 16
> 
> Fatal error: Declaration of BeyondCode\DuskDashboard\Testing\TestCase::onNotSuccessfulTest(Throwable $t) must be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t): void in /home/vagrant/faaren/repositories/website-and-consumer-area/vendor/beyondcode/dusk-dashboard/src/Testing/TestCase.php on line 16

I'm using phpunit 8 and Laravel 5.8

**Comment by MCMainiac** [comment]
Related to #38 and fixed in #39

**Comment by Braunson** [comment]
Updated and tried again but still having the issue where the frame shows nothing (but the url..  i.e. `/login`), tests run tho.

**Comment by carlosalzate74** [comment]
Running Laravel 5.8, Dusk 5.4, phpunit 7.5 (which fixed the incompatible declaration of onNotSuccessfulTest).

I started my php artisan dusk:dashboard using console, dashboard opens, hit Start Tests, tests ran in the console but nothing shows up in the dashboard.

Any idea?

**Comment by angusm73** [comment]
Getting the same issue here.

Running:
Laravel 5.8.35
Dusk 5.5.2
PHPunit 7.5.16

**Comment by xaniuskarlhall** [comment]
Experiencing the same issue

**Comment by dewelooper** [comment]
me too :(
